### ISSUE TITLE
'Use Retrotouch' setting always defaults to 'ON' despite UI setting

### ISSUE THREAD

**Issue by Icon125** [Rinnegatamante/Quakespasm#2]
Regardless if one exits the game with 'Use Retrotouch' enabled or disabled in the UI, Quakespasm will re-enable it in-game, ignoring its setting in the UI.

To disable it, it must be flicked from off, to on, to off again each time before playing.

**Comment by Rinnegatamante** [comment]
Solved with v.1.6
