### ISSUE TITLE
Textures will occasionally glitch

### ISSUE THREAD

**Issue by Icon125** [Rinnegatamante/Quakespasm#4]
This seems to occur most often at the first load of a level, re-loading the level will 'fix' it.

![glitch](https://user-images.githubusercontent.com/82722404/174219749-ee09926e-469c-4eba-99f8-36106f3fd5d1.png)

![noglitch](https://user-images.githubusercontent.com/82722404/174219782-068fd04b-ae43-4ab5-b45b-3fec58564a3e.png)

**Comment by garymohan** [comment]
It's very noticeable on many mods, for example the first level of Dimensions of the Past (dopa).

**Comment by Sarkie** [comment]
This is occurring mainly on ammo boxes. Cell and Rockets

**Comment by Rinnegatamante** [comment]
Do you guys have an easy way to reproduce this 100% times?

**Comment by garymohan** [comment]
Go through the first level of Dimensions of the Past (DOPA).

**Comment by Rinnegatamante** [comment]
Can't reproduce the issue. Can you try to reproduce it with this build and see if it happens?

[quakespasm.zip](https://github.com/Rinnegatamante/Quakespasm/files/10420575/quakespasm.zip)

**Comment by garymohan** [comment]
Yeah, that seems to fix it.  Thanks!

**Comment by Rinnegatamante** [comment]
Solved with v.1.6
