### ISSUE TITLE
'Water Opacity' slider does not affect water opacity, geometry can be seen through water.

### ISSUE THREAD

**Issue by Icon125** [Rinnegatamante/Quakespasm#5]
See attached screenshots.

Error: "Warning: Map does not appear to be water-vised."

![glitch](https://user-images.githubusercontent.com/82722404/174696615-5bc97f77-4529-4146-9b40-0d30b26c032b.png)
![glitch2](https://user-images.githubusercontent.com/82722404/174696620-7f1bc6b2-63bd-43ae-bab9-493b68c19e79.png)
![seethrough](https://user-images.githubusercontent.com/82722404/174696624-6cc00dc0-e0c3-43e4-b9bf-59cfe3faa0dd.png)

**Comment by Rinnegatamante** [comment]
As the engine suggests, you need a properly vis-ed map to have proper transparency.

**Comment by Rinnegatamante** [comment]
![immagine](https://user-images.githubusercontent.com/9152710/212534729-8f46888b-85a5-40ce-9e23-5877a699b377.png)
Not reproducible with properly vis-ed pak files.
